# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/asautaux/yarr/project_pcie_6/project_pcie_6.srcs/sources_1/ip/ila_wsh_pipe/ila_wsh_pipe.xci
# IP: The module: 'ila_wsh_pipe' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/asautaux/yarr/project_pcie_6/project_pcie_6.srcs/sources_1/ip/ila_wsh_pipe/ila_v6_1/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_wsh_pipe'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/asautaux/yarr/project_pcie_6/project_pcie_6.srcs/sources_1/ip/ila_wsh_pipe/ila_wsh_pipe_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_wsh_pipe'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/asautaux/yarr/project_pcie_6/project_pcie_6.srcs/sources_1/ip/ila_wsh_pipe/ila_wsh_pipe.xci
# IP: The module: 'ila_wsh_pipe' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/asautaux/yarr/project_pcie_6/project_pcie_6.srcs/sources_1/ip/ila_wsh_pipe/ila_v6_1/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_wsh_pipe'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/asautaux/yarr/project_pcie_6/project_pcie_6.srcs/sources_1/ip/ila_wsh_pipe/ila_wsh_pipe_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_wsh_pipe'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
