##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Mon May 22 11:50:28 2017
##  Generated by MIG Version 4.0
##  
##################################################################################################
##  File name :       example_top.sdc
##  Details :     Constraints file
##                    FPGA Family:       KINTEX7
##                    FPGA Part:         XC7K160TIFBG676_PKG
##                    Speedgrade:        -2
##                    Design Entry:      VHDL
##                    Frequency:         0 MHz
##                    Time Period:       1875 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->Components->MT41K256M8XX-125
## Data Width: 64
## Time Period: 1875
## Data Mask: 1
##################################################################################################

create_clock -period 5 [get_ports sys_clk_p]
          
############## NET - IOSTANDARD ##################


