# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k160tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/asautaux/yarr/project_hdl/project_hdl.cache/wt [current_project]
set_property parent.project_path /home/asautaux/yarr/project_hdl/project_hdl.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
add_files -quiet /home/asautaux/yarr/project_hdl/project_hdl.srcs/sources_1/ip/ila_0/ila_0.dcp
set_property used_in_implementation false [get_files /home/asautaux/yarr/project_hdl/project_hdl.srcs/sources_1/ip/ila_0/ila_0.dcp]
read_vhdl -library xil_defaultlib {
  /home/asautaux/yarr/project_hdl/ram_interface.vhd
  /home/asautaux/yarr/project_hdl/ram_ctrl.vhd
  /home/asautaux/yarr/project_hdl/simple_counter.vhd
  /home/asautaux/yarr/project_hdl/test_bench.vhd
  /home/asautaux/yarr/project_hdl/top_level.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/asautaux/yarr/project_hdl/project_hdl.srcs/constrs_1/imports/project_hdl/project_2.xdc
set_property used_in_implementation false [get_files /home/asautaux/yarr/project_hdl/project_hdl.srcs/constrs_1/imports/project_hdl/project_2.xdc]


synth_design -top top_level -part xc7k160tfbg676-2


write_checkpoint -force -noxdef top_level.dcp

catch { report_utilization -file top_level_utilization_synth.rpt -pb top_level_utilization_synth.pb }
