# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/asautaux/yarr/pcie_7x_0_example/pcie_7x_0_example.srcs/sources_1/ip/pcie_7x_0/pcie_7x_0.xci
# IP: The module: 'pcie_7x_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/asautaux/yarr/pcie_7x_0_example/pcie_7x_0_example.srcs/sources_1/ip/pcie_7x_0/ip_0/pcie_7x_0_fastConfigFIFO.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_7x_0_fastConfigFIFO || ORIG_REF_NAME==pcie_7x_0_fastConfigFIFO}]

# XDC: /home/asautaux/yarr/pcie_7x_0_example/pcie_7x_0_example.srcs/sources_1/ip/pcie_7x_0/source/pcie_7x_0-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_7x_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/asautaux/yarr/pcie_7x_0_example/pcie_7x_0_example.srcs/sources_1/ip/pcie_7x_0/synth/pcie_7x_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_7x_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/asautaux/yarr/pcie_7x_0_example/pcie_7x_0_example.srcs/sources_1/ip/pcie_7x_0/ip_0/pcie_7x_0_fastConfigFIFO/pcie_7x_0_fastConfigFIFO_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_7x_0_fastConfigFIFO || ORIG_REF_NAME==pcie_7x_0_fastConfigFIFO}] {/U0 }]/U0 ]]

# XDC: /home/asautaux/yarr/pcie_7x_0_example/pcie_7x_0_example.srcs/sources_1/ip/pcie_7x_0/ip_0/pcie_7x_0_fastConfigFIFO/pcie_7x_0_fastConfigFIFO.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_7x_0_fastConfigFIFO || ORIG_REF_NAME==pcie_7x_0_fastConfigFIFO}] {/U0 }]/U0 ]]

# XDC: /home/asautaux/yarr/pcie_7x_0_example/pcie_7x_0_example.srcs/sources_1/ip/pcie_7x_0/ip_0/pcie_7x_0_fastConfigFIFO_ooc.xdc

# IP: /home/asautaux/yarr/pcie_7x_0_example/pcie_7x_0_example.srcs/sources_1/ip/pcie_7x_0/pcie_7x_0.xci
# IP: The module: 'pcie_7x_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/asautaux/yarr/pcie_7x_0_example/pcie_7x_0_example.srcs/sources_1/ip/pcie_7x_0/ip_0/pcie_7x_0_fastConfigFIFO.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_7x_0_fastConfigFIFO || ORIG_REF_NAME==pcie_7x_0_fastConfigFIFO}]

# XDC: /home/asautaux/yarr/pcie_7x_0_example/pcie_7x_0_example.srcs/sources_1/ip/pcie_7x_0/source/pcie_7x_0-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_7x_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/asautaux/yarr/pcie_7x_0_example/pcie_7x_0_example.srcs/sources_1/ip/pcie_7x_0/synth/pcie_7x_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_7x_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/asautaux/yarr/pcie_7x_0_example/pcie_7x_0_example.srcs/sources_1/ip/pcie_7x_0/ip_0/pcie_7x_0_fastConfigFIFO/pcie_7x_0_fastConfigFIFO_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_7x_0_fastConfigFIFO || ORIG_REF_NAME==pcie_7x_0_fastConfigFIFO}] {/U0 }]/U0 ]]

# XDC: /home/asautaux/yarr/pcie_7x_0_example/pcie_7x_0_example.srcs/sources_1/ip/pcie_7x_0/ip_0/pcie_7x_0_fastConfigFIFO/pcie_7x_0_fastConfigFIFO.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_7x_0_fastConfigFIFO || ORIG_REF_NAME==pcie_7x_0_fastConfigFIFO}] {/U0 }]/U0 ]]

# XDC: /home/asautaux/yarr/pcie_7x_0_example/pcie_7x_0_example.srcs/sources_1/ip/pcie_7x_0/ip_0/pcie_7x_0_fastConfigFIFO_ooc.xdc
