# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7k160tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/asautaux/yarr/simple_pcie/simple_pcie.cache/wt [current_project]
set_property parent.project_path /home/asautaux/yarr/simple_pcie/simple_pcie.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property include_dirs {
  /home/asautaux/vhdl/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/quickpcie/include/common
  {/home/asautaux/vhdl/quickpcie-expert_gen2_v156_b085_xilinx_eval/ref_design/synthesis/xilinx/plda_xpressk7_xc7k160tfbg676-2/x4_gen2/vlog/;}
  /home/asautaux/vhdl/quickpcie-expert_gen2_v156_b085_xilinx_eval/ref_design/source/endpoint/design/wrapper/k7/qpcie_ipcore_x4_gen2
} [current_fileset]
read_ip -quiet /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/ip/ila_3/ila_3.xci
set_property is_locked true [get_files /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/ip/ila_3/ila_3.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top ila_3 -part xc7k160tfbg676-2 -mode out_of_context

rename_ref -prefix_all ila_3_

write_checkpoint -force -noxdef ila_3.dcp

catch { report_utilization -file ila_3_utilization_synth.rpt -pb ila_3_utilization_synth.pb }

if { [catch {
  write_verilog -force -mode synth_stub /home/asautaux/yarr/simple_pcie/simple_pcie.runs/ila_3_synth_1/ila_3_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/asautaux/yarr/simple_pcie/simple_pcie.runs/ila_3_synth_1/ila_3_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/asautaux/yarr/simple_pcie/simple_pcie.runs/ila_3_synth_1/ila_3_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/asautaux/yarr/simple_pcie/simple_pcie.runs/ila_3_synth_1/ila_3_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

add_files /home/asautaux/yarr/simple_pcie/simple_pcie.runs/ila_3_synth_1/ila_3_stub.v -of_objects [get_files /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/ip/ila_3/ila_3.xci]

add_files /home/asautaux/yarr/simple_pcie/simple_pcie.runs/ila_3_synth_1/ila_3_stub.vhdl -of_objects [get_files /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/ip/ila_3/ila_3.xci]

add_files /home/asautaux/yarr/simple_pcie/simple_pcie.runs/ila_3_synth_1/ila_3_sim_netlist.v -of_objects [get_files /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/ip/ila_3/ila_3.xci]

add_files /home/asautaux/yarr/simple_pcie/simple_pcie.runs/ila_3_synth_1/ila_3_sim_netlist.vhdl -of_objects [get_files /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/ip/ila_3/ila_3.xci]

add_files /home/asautaux/yarr/simple_pcie/simple_pcie.runs/ila_3_synth_1/ila_3.dcp -of_objects [get_files /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/ip/ila_3/ila_3.xci]

if {[file isdir /home/asautaux/yarr/simple_pcie/simple_pcie.ip_user_files/ip/ila_3]} {
  catch { 
    file copy -force /home/asautaux/yarr/simple_pcie/simple_pcie.runs/ila_3_synth_1/ila_3_sim_netlist.v /home/asautaux/yarr/simple_pcie/simple_pcie.ip_user_files/ip/ila_3
  }
}

if {[file isdir /home/asautaux/yarr/simple_pcie/simple_pcie.ip_user_files/ip/ila_3]} {
  catch { 
    file copy -force /home/asautaux/yarr/simple_pcie/simple_pcie.runs/ila_3_synth_1/ila_3_sim_netlist.vhdl /home/asautaux/yarr/simple_pcie/simple_pcie.ip_user_files/ip/ila_3
  }
}

if {[file isdir /home/asautaux/yarr/simple_pcie/simple_pcie.ip_user_files/ip/ila_3]} {
  catch { 
    file copy -force /home/asautaux/yarr/simple_pcie/simple_pcie.runs/ila_3_synth_1/ila_3_stub.v /home/asautaux/yarr/simple_pcie/simple_pcie.ip_user_files/ip/ila_3
  }
}

if {[file isdir /home/asautaux/yarr/simple_pcie/simple_pcie.ip_user_files/ip/ila_3]} {
  catch { 
    file copy -force /home/asautaux/yarr/simple_pcie/simple_pcie.runs/ila_3_synth_1/ila_3_stub.vhdl /home/asautaux/yarr/simple_pcie/simple_pcie.ip_user_files/ip/ila_3
  }
}
