# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-5009-spikepig.dhcp.lbl.gov/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7k160tfbg676-2
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/asautaux/yarr/project_pcie_6/project_pcie_6.srcs/sources_1/ip/ila_pd_pdm/ltlib_v1_0_0/hdl/verilog
    /home/asautaux/yarr/project_pcie_6/project_pcie_6.srcs/sources_1/ip/ila_pd_pdm/xsdbs_v1_0_2/hdl/verilog
    /home/asautaux/yarr/project_pcie_6/project_pcie_6.srcs/sources_1/ip/ila_pd_pdm/xsdbm_v1_1_3/hdl/verilog
    /home/asautaux/yarr/project_pcie_6/project_pcie_6.srcs/sources_1/ip/ila_pd_pdm/ila_v6_1_1/hdl/verilog
  } {
      /opt/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /opt/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_base.sv
      /opt/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_dpdistram.sv
      /opt/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_dprom.sv
      /opt/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_sdpram.sv
      /opt/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_spram.sv
      /opt/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_sprom.sv
      /opt/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_tdpram.sv
    }
      rt::read_verilog -include {
    /home/asautaux/yarr/project_pcie_6/project_pcie_6.srcs/sources_1/ip/ila_pd_pdm/ltlib_v1_0_0/hdl/verilog
    /home/asautaux/yarr/project_pcie_6/project_pcie_6.srcs/sources_1/ip/ila_pd_pdm/xsdbs_v1_0_2/hdl/verilog
    /home/asautaux/yarr/project_pcie_6/project_pcie_6.srcs/sources_1/ip/ila_pd_pdm/xsdbm_v1_1_3/hdl/verilog
    /home/asautaux/yarr/project_pcie_6/project_pcie_6.srcs/sources_1/ip/ila_pd_pdm/ila_v6_1_1/hdl/verilog
  } {
      /home/asautaux/yarr/project_pcie_6/project_pcie_6.srcs/sources_1/ip/ila_pd_pdm/ltlib_v1_0_0/hdl/ltlib_v1_0_vl_rfs.v
      /home/asautaux/yarr/project_pcie_6/project_pcie_6.srcs/sources_1/ip/ila_pd_pdm/xsdbs_v1_0_2/hdl/xsdbs_v1_0_vl_rfs.v
      /home/asautaux/yarr/project_pcie_6/project_pcie_6.srcs/sources_1/ip/ila_pd_pdm/xsdbm_v1_1_3/hdl/xsdbm_v1_1_vl_rfs.v
      /home/asautaux/yarr/project_pcie_6/project_pcie_6.srcs/sources_1/ip/ila_pd_pdm/xsdbm_v1_1_3/hdl/verilog/xsdbm_v1_1_xsdbm.v
      /home/asautaux/yarr/project_pcie_6/project_pcie_6.srcs/sources_1/ip/ila_pd_pdm/ila_v6_1_1/hdl/ila_v6_1_syn_rfs.v
    }
      rt::read_vhdl -lib blk_mem_gen_v8_3_3 {
      /home/asautaux/yarr/project_pcie_6/project_pcie_6.srcs/sources_1/ip/ila_pd_pdm/blk_mem_gen_v8_3_3/hdl/blk_mem_gen_v8_3_vhsyn_rfs.vhd
      /home/asautaux/yarr/project_pcie_6/project_pcie_6.srcs/sources_1/ip/ila_pd_pdm/blk_mem_gen_v8_3_3/hdl/blk_mem_gen_v8_3.vhd
    }
      rt::read_vhdl -lib fifo_generator_v13_0_3 {
      /home/asautaux/yarr/project_pcie_6/project_pcie_6.srcs/sources_1/ip/ila_pd_pdm/fifo_generator_v13_0_3/hdl/fifo_generator_v13_0_vhsyn_rfs.vhd
      /home/asautaux/yarr/project_pcie_6/project_pcie_6.srcs/sources_1/ip/ila_pd_pdm/fifo_generator_v13_0_3/hdl/fifo_generator_v13_0.vhd
    }
      rt::read_vhdl -lib xil_defaultlib /home/asautaux/yarr/project_pcie_6/project_pcie_6.srcs/sources_1/ip/ila_pd_pdm/synth/ila_pd_pdm.vhd
      rt::read_vhdl -lib xpm /opt/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top ila_pd_pdm
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-5009-spikepig.dhcp.lbl.gov/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
      rt::run_rtlelab -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }


    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
