set_property SRC_FILE_INFO {cfile:/home/asautaux/yarr/project_pcie_6/project_pcie_6.srcs/constrs_1/imports/new/project_2.xdc rfile:../../../project_pcie_6.srcs/constrs_1/imports/new/project_2.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:/home/asautaux/yarr/project_pcie_6/project_pcie_6.srcs/constrs_1/imports/Documents/ddr3.xdc rfile:../../../project_pcie_6.srcs/constrs_1/imports/Documents/ddr3.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA10 [get_ports clk200_p]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D6 [get_ports pcie_clk_p]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D5 [get_ports pcie_clk_n]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X0Y7 [get_cells {pcie_0/U0/inst/gt_top_i/pipe_wrapper_i/pipe_lane[0].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B5 [get_ports {pci_exp_rxn[0]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B6 [get_ports {pci_exp_rxp[0]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X0Y6 [get_cells {pcie_0/U0/inst/gt_top_i/pipe_wrapper_i/pipe_lane[1].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C3 [get_ports {pci_exp_rxn[1]}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C4 [get_ports {pci_exp_rxp[1]}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X0Y5 [get_cells {pcie_0/U0/inst/gt_top_i/pipe_wrapper_i/pipe_lane[2].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports {pci_exp_rxn[2]}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E4 [get_ports {pci_exp_rxp[2]}]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X0Y4 [get_cells {pcie_0/U0/inst/gt_top_i/pipe_wrapper_i/pipe_lane[3].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G3 [get_ports {pci_exp_rxn[3]}]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G4 [get_ports {pci_exp_rxp[3]}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y20 [get_ports rst_n_i]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W10 [get_ports {usr_led_o[0]}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V11 [get_ports {usr_led_o[1]}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y10 [get_ports {usr_led_o[2]}]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA15 [get_ports {usr_sw_i[0]}]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V8 [get_ports {usr_sw_i[1]}]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y8 [get_ports {usr_sw_i[2]}]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports sys_rst_n_i]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC V17 [get_ports {ddr3_dq[0]}]
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC V19 [get_ports {ddr3_dq[1]}]
set_property src_info {type:XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC V16 [get_ports {ddr3_dq[2]}]
set_property src_info {type:XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC Y17 [get_ports {ddr3_dq[3]}]
set_property src_info {type:XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC W16 [get_ports {ddr3_dq[4]}]
set_property src_info {type:XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC W15 [get_ports {ddr3_dq[5]}]
set_property src_info {type:XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC W14 [get_ports {ddr3_dq[6]}]
set_property src_info {type:XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC V14 [get_ports {ddr3_dq[7]}]
set_property src_info {type:XDC file:2 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AA19 [get_ports {ddr3_dq[8]}]
set_property src_info {type:XDC file:2 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AA20 [get_ports {ddr3_dq[9]}]
set_property src_info {type:XDC file:2 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD19 [get_ports {ddr3_dq[10]}]
set_property src_info {type:XDC file:2 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD18 [get_ports {ddr3_dq[11]}]
set_property src_info {type:XDC file:2 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AB20 [get_ports {ddr3_dq[12]}]
set_property src_info {type:XDC file:2 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AC19 [get_ports {ddr3_dq[13]}]
set_property src_info {type:XDC file:2 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AC17 [get_ports {ddr3_dq[14]}]
set_property src_info {type:XDC file:2 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AB17 [get_ports {ddr3_dq[15]}]
set_property src_info {type:XDC file:2 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AA17 [get_ports {ddr3_dq[16]}]
set_property src_info {type:XDC file:2 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AA18 [get_ports {ddr3_dq[17]}]
set_property src_info {type:XDC file:2 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AC14 [get_ports {ddr3_dq[18]}]
set_property src_info {type:XDC file:2 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AB15 [get_ports {ddr3_dq[19]}]
set_property src_info {type:XDC file:2 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AB16 [get_ports {ddr3_dq[20]}]
set_property src_info {type:XDC file:2 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AC16 [get_ports {ddr3_dq[21]}]
set_property src_info {type:XDC file:2 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AB14 [get_ports {ddr3_dq[22]}]
set_property src_info {type:XDC file:2 line:289 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AA14 [get_ports {ddr3_dq[23]}]
set_property src_info {type:XDC file:2 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AF20 [get_ports {ddr3_dq[24]}]
set_property src_info {type:XDC file:2 line:313 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AE17 [get_ports {ddr3_dq[25]}]
set_property src_info {type:XDC file:2 line:325 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AF17 [get_ports {ddr3_dq[26]}]
set_property src_info {type:XDC file:2 line:337 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD16 [get_ports {ddr3_dq[27]}]
set_property src_info {type:XDC file:2 line:349 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AF15 [get_ports {ddr3_dq[28]}]
set_property src_info {type:XDC file:2 line:361 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AE15 [get_ports {ddr3_dq[29]}]
set_property src_info {type:XDC file:2 line:373 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD15 [get_ports {ddr3_dq[30]}]
set_property src_info {type:XDC file:2 line:385 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AF14 [get_ports {ddr3_dq[31]}]
set_property src_info {type:XDC file:2 line:397 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AE6 [get_ports {ddr3_dq[32]}]
set_property src_info {type:XDC file:2 line:409 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AE5 [get_ports {ddr3_dq[33]}]
set_property src_info {type:XDC file:2 line:421 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AE3 [get_ports {ddr3_dq[34]}]
set_property src_info {type:XDC file:2 line:433 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AF2 [get_ports {ddr3_dq[35]}]
set_property src_info {type:XDC file:2 line:445 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD4 [get_ports {ddr3_dq[36]}]
set_property src_info {type:XDC file:2 line:457 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AF3 [get_ports {ddr3_dq[37]}]
set_property src_info {type:XDC file:2 line:469 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD1 [get_ports {ddr3_dq[38]}]
set_property src_info {type:XDC file:2 line:481 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AE1 [get_ports {ddr3_dq[39]}]
set_property src_info {type:XDC file:2 line:493 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD6 [get_ports {ddr3_dq[40]}]
set_property src_info {type:XDC file:2 line:505 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC Y6 [get_ports {ddr3_dq[41]}]
set_property src_info {type:XDC file:2 line:517 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC Y5 [get_ports {ddr3_dq[42]}]
set_property src_info {type:XDC file:2 line:529 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AA4 [get_ports {ddr3_dq[43]}]
set_property src_info {type:XDC file:2 line:541 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AB6 [get_ports {ddr3_dq[44]}]
set_property src_info {type:XDC file:2 line:553 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AC6 [get_ports {ddr3_dq[45]}]
set_property src_info {type:XDC file:2 line:565 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AB4 [get_ports {ddr3_dq[46]}]
set_property src_info {type:XDC file:2 line:577 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AC3 [get_ports {ddr3_dq[47]}]
set_property src_info {type:XDC file:2 line:589 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AC2 [get_ports {ddr3_dq[48]}]
set_property src_info {type:XDC file:2 line:601 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AA2 [get_ports {ddr3_dq[49]}]
set_property src_info {type:XDC file:2 line:613 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC Y3 [get_ports {ddr3_dq[50]}]
set_property src_info {type:XDC file:2 line:625 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC Y1 [get_ports {ddr3_dq[51]}]
set_property src_info {type:XDC file:2 line:637 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AA3 [get_ports {ddr3_dq[52]}]
set_property src_info {type:XDC file:2 line:649 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AB2 [get_ports {ddr3_dq[53]}]
set_property src_info {type:XDC file:2 line:661 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC V1 [get_ports {ddr3_dq[54]}]
set_property src_info {type:XDC file:2 line:673 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC W1 [get_ports {ddr3_dq[55]}]
set_property src_info {type:XDC file:2 line:685 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC V3 [get_ports {ddr3_dq[56]}]
set_property src_info {type:XDC file:2 line:697 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC W3 [get_ports {ddr3_dq[57]}]
set_property src_info {type:XDC file:2 line:709 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC U1 [get_ports {ddr3_dq[58]}]
set_property src_info {type:XDC file:2 line:721 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC U2 [get_ports {ddr3_dq[59]}]
set_property src_info {type:XDC file:2 line:733 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC U7 [get_ports {ddr3_dq[60]}]
set_property src_info {type:XDC file:2 line:745 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC V6 [get_ports {ddr3_dq[61]}]
set_property src_info {type:XDC file:2 line:757 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC U6 [get_ports {ddr3_dq[62]}]
set_property src_info {type:XDC file:2 line:769 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC V4 [get_ports {ddr3_dq[63]}]
set_property src_info {type:XDC file:2 line:775 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_addr[15]}]
set_property src_info {type:XDC file:2 line:777 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[15]}]
set_property src_info {type:XDC file:2 line:779 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[15]}]
set_property src_info {type:XDC file:2 line:781 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AF9 [get_ports {ddr3_addr[15]}]
set_property src_info {type:XDC file:2 line:793 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD10 [get_ports {ddr3_addr[14]}]
set_property src_info {type:XDC file:2 line:805 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AA7 [get_ports {ddr3_addr[13]}]
set_property src_info {type:XDC file:2 line:817 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AF10 [get_ports {ddr3_addr[12]}]
set_property src_info {type:XDC file:2 line:829 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AC9 [get_ports {ddr3_addr[11]}]
set_property src_info {type:XDC file:2 line:841 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AB7 [get_ports {ddr3_addr[10]}]
set_property src_info {type:XDC file:2 line:853 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AE10 [get_ports {ddr3_addr[9]}]
set_property src_info {type:XDC file:2 line:865 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AA9 [get_ports {ddr3_addr[8]}]
set_property src_info {type:XDC file:2 line:877 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AE8 [get_ports {ddr3_addr[7]}]
set_property src_info {type:XDC file:2 line:889 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AF8 [get_ports {ddr3_addr[6]}]
set_property src_info {type:XDC file:2 line:901 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AB9 [get_ports {ddr3_addr[5]}]
set_property src_info {type:XDC file:2 line:913 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD8 [get_ports {ddr3_addr[4]}]
set_property src_info {type:XDC file:2 line:925 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD9 [get_ports {ddr3_addr[3]}]
set_property src_info {type:XDC file:2 line:937 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AF7 [get_ports {ddr3_addr[2]}]
set_property src_info {type:XDC file:2 line:949 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AE7 [get_ports {ddr3_addr[1]}]
set_property src_info {type:XDC file:2 line:961 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AC7 [get_ports {ddr3_addr[0]}]
set_property src_info {type:XDC file:2 line:973 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD13 [get_ports {ddr3_ba[2]}]
set_property src_info {type:XDC file:2 line:985 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AC12 [get_ports {ddr3_ba[1]}]
set_property src_info {type:XDC file:2 line:997 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AB12 [get_ports {ddr3_ba[0]}]
set_property src_info {type:XDC file:2 line:1009 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AE11 [get_ports {ddr3_ras_n}]
set_property src_info {type:XDC file:2 line:1021 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC Y12 [get_ports {ddr3_cas_n}]
set_property src_info {type:XDC file:2 line:1033 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AC11 [get_ports {ddr3_we_n}]
set_property src_info {type:XDC file:2 line:1045 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AA13 [get_ports {ddr3_reset_n}]
set_property src_info {type:XDC file:2 line:1057 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AA12 [get_ports {ddr3_cke[0]}]
set_property src_info {type:XDC file:2 line:1069 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AC8 [get_ports {ddr3_odt[0]}]
set_property src_info {type:XDC file:2 line:1081 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD11 [get_ports {ddr3_cs_n[0]}]
set_property src_info {type:XDC file:2 line:1093 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC V18 [get_ports {ddr3_dm[0]}]
set_property src_info {type:XDC file:2 line:1105 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AC18 [get_ports {ddr3_dm[1]}]
set_property src_info {type:XDC file:2 line:1117 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD14 [get_ports {ddr3_dm[2]}]
set_property src_info {type:XDC file:2 line:1129 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AF19 [get_ports {ddr3_dm[3]}]
set_property src_info {type:XDC file:2 line:1141 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AE2 [get_ports {ddr3_dm[4]}]
set_property src_info {type:XDC file:2 line:1153 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AC4 [get_ports {ddr3_dm[5]}]
set_property src_info {type:XDC file:2 line:1165 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC Y2 [get_ports {ddr3_dm[6]}]
set_property src_info {type:XDC file:2 line:1177 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC U5 [get_ports {ddr3_dm[7]}]
set_property src_info {type:XDC file:2 line:1233 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC W18 [get_ports {ddr3_dqs_p[0]}]
set_property src_info {type:XDC file:2 line:1245 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC W19 [get_ports {ddr3_dqs_n[0]}]
set_property src_info {type:XDC file:2 line:1257 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD20 [get_ports {ddr3_dqs_p[1]}]
set_property src_info {type:XDC file:2 line:1269 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AE20 [get_ports {ddr3_dqs_n[1]}]
set_property src_info {type:XDC file:2 line:1281 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC Y15 [get_ports {ddr3_dqs_p[2]}]
set_property src_info {type:XDC file:2 line:1293 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC Y16 [get_ports {ddr3_dqs_n[2]}]
set_property src_info {type:XDC file:2 line:1305 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AE18 [get_ports {ddr3_dqs_p[3]}]
set_property src_info {type:XDC file:2 line:1317 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AF18 [get_ports {ddr3_dqs_n[3]}]
set_property src_info {type:XDC file:2 line:1329 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AF5 [get_ports {ddr3_dqs_p[4]}]
set_property src_info {type:XDC file:2 line:1341 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AF4 [get_ports {ddr3_dqs_n[4]}]
set_property src_info {type:XDC file:2 line:1353 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AA5 [get_ports {ddr3_dqs_p[5]}]
set_property src_info {type:XDC file:2 line:1365 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AB5 [get_ports {ddr3_dqs_n[5]}]
set_property src_info {type:XDC file:2 line:1377 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AB1 [get_ports {ddr3_dqs_p[6]}]
set_property src_info {type:XDC file:2 line:1389 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AC1 [get_ports {ddr3_dqs_n[6]}]
set_property src_info {type:XDC file:2 line:1401 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC W6 [get_ports {ddr3_dqs_p[7]}]
set_property src_info {type:XDC file:2 line:1413 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC W5 [get_ports {ddr3_dqs_n[7]}]
set_property src_info {type:XDC file:2 line:1425 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AE13 [get_ports {ddr3_ck_p[0]}]
set_property src_info {type:XDC file:2 line:1437 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AF13 [get_ports {ddr3_ck_n[0]}]
set_property src_info {type:XDC file:2 line:1443 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_cs_n[1]}]
set_property src_info {type:XDC file:2 line:1445 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_cs_n[1]}]
set_property src_info {type:XDC file:2 line:1447 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_cs_n[1]}]
set_property src_info {type:XDC file:2 line:1449 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC Y11 [get_ports {ddr3_cs_n[1]}]
set_property src_info {type:XDC file:2 line:1453 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO NORMAL [get_ports {ddr3_odt[1]}]
set_property src_info {type:XDC file:2 line:1455 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_odt[1]}]
set_property src_info {type:XDC file:2 line:1457 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_odt[1]}]
set_property src_info {type:XDC file:2 line:1459 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AA8 [get_ports {ddr3_odt[1]}]
