# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/asautaux/yarr/project_pcie_3/project_pcie_3.srcs/sources_1/ip/axi_mm2s_mapper_0/axi_mm2s_mapper_0.xci
# IP: The module: 'axi_mm2s_mapper_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/asautaux/yarr/project_pcie_3/project_pcie_3.srcs/sources_1/ip/axi_mm2s_mapper_0/axi_mm2s_mapper_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_mm2s_mapper_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/asautaux/yarr/project_pcie_3/project_pcie_3.srcs/sources_1/ip/axi_mm2s_mapper_0/axi_mm2s_mapper_0.xci
# IP: The module: 'axi_mm2s_mapper_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/asautaux/yarr/project_pcie_3/project_pcie_3.srcs/sources_1/ip/axi_mm2s_mapper_0/axi_mm2s_mapper_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_mm2s_mapper_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
