##################################################################################################
##
##  Xilinx, Inc. 2010            www.xilinx.com
##  Tue May 2 16:14:16 2017
##  Generated by MIG Version 4.0
##
##################################################################################################
##  File name :       example_top.xdc
##  Details :     Constraints file
##                    FPGA Family:       KINTEX7
##                    FPGA Part:         XC7K160T-FBG676
##                    Speedgrade:        -2
##                    Design Entry:      VHDL
##                    Frequency:         0 MHz
##                    Time Period:       1875 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->Components->MT41K256M8XX-125
## Data Width: 64
## Time Period: 1875
## Data Mask: 1
##################################################################################################
############## NET - IOSTANDARD ##################



set_property IOSTANDARD LVCMOS15 [get_ports sys_rst_n_i]
set_property PACKAGE_PIN U16 [get_ports sys_rst_n_i]

set_property IOSTANDARD LVCMOS15 [get_ports init_calib_complete]
set_property IOSTANDARD LVCMOS15 [get_ports tg_compare_error]
set_property PACKAGE_PIN W10 [get_ports init_calib_complete]
set_property PACKAGE_PIN V11 [get_ports tg_compare_error]
