# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7k160tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/asautaux/yarr/project_pcie_4/project_pcie_4.cache/wt [current_project]
set_property parent.project_path /home/asautaux/yarr/project_pcie_4/project_pcie_4.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
add_files -quiet /home/asautaux/yarr/project_pcie_4/project_pcie_4.srcs/sources_1/ip/pcie_7x_0/pcie_7x_0.dcp
set_property used_in_implementation false [get_files /home/asautaux/yarr/project_pcie_4/project_pcie_4.srcs/sources_1/ip/pcie_7x_0/pcie_7x_0.dcp]
add_files /home/asautaux/yarr/project_pcie_4/project_pcie_4.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/asautaux/yarr/project_pcie_4/project_pcie_4.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_0_0/design_1_util_ds_buf_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/asautaux/yarr/project_pcie_4/project_pcie_4.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files /home/asautaux/yarr/project_pcie_4/project_pcie_4.srcs/sources_1/bd/design_1/design_1.bd]

read_vhdl -library xil_defaultlib {
  /home/asautaux/yarr/project_pcie_4/project_pcie_4.srcs/sources_1/imports/sources_1/imports/sources_1/imports/new/simple_counter.vhd
  /home/asautaux/yarr/project_pcie_4/project_pcie_4.srcs/sources_1/imports/Downloads/bcf_bram_wbs.vhd
  /home/asautaux/yarr/project_pcie_4/project_pcie_4.srcs/sources_1/imports/Downloads/axis_rx.vhd
  /home/asautaux/yarr/project_pcie_4/project_pcie_4.srcs/sources_1/new/app.vhd
  /home/asautaux/yarr/project_pcie_4/project_pcie_4.srcs/sources_1/imports/sources_1/imports/sources_1/new/top_level.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/asautaux/yarr/project_pcie_4/project_pcie_4.srcs/constrs_1/imports/new/project_2.xdc
set_property used_in_implementation false [get_files /home/asautaux/yarr/project_pcie_4/project_pcie_4.srcs/constrs_1/imports/new/project_2.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top_level -part xc7k160tfbg676-2


write_checkpoint -force -noxdef top_level.dcp

catch { report_utilization -file top_level_utilization_synth.rpt -pb top_level_utilization_synth.pb }
