set_property PACKAGE_PIN L23 [get_ports sys_rst_n]

#PCIe signals
set_property PACKAGE_PIN G4 [get_ports {pcie_7x_mgt_rxp[3]}]
set_property PACKAGE_PIN G3 [get_ports {pcie_7x_mgt_rxn[3]}]
set_property PACKAGE_PIN E4 [get_ports {pcie_7x_mgt_rxp[2]}]
set_property PACKAGE_PIN E3 [get_ports {pcie_7x_mgt_rxn[2]}]
set_property PACKAGE_PIN C4 [get_ports {pcie_7x_mgt_rxp[1]}]
set_property PACKAGE_PIN C3 [get_ports {pcie_7x_mgt_rxn[1]}]
set_property PACKAGE_PIN B6 [get_ports {pcie_7x_mgt_rxp[0]}]
set_property PACKAGE_PIN B5 [get_ports {pcie_7x_mgt_rxn[0]}]

set_property PACKAGE_PIN F2 [get_ports {pcie_7x_mgt_txp[3]}]
set_property PACKAGE_PIN F1 [get_ports {pcie_7x_mgt_txn[3]}]
set_property PACKAGE_PIN D2 [get_ports {pcie_7x_mgt_txp[2]}]
set_property PACKAGE_PIN D1 [get_ports {pcie_7x_mgt_txn[2]}]
set_property PACKAGE_PIN B2 [get_ports {pcie_7x_mgt_txp[1]}]
set_property PACKAGE_PIN B1 [get_ports {pcie_7x_mgt_txn[1]}]
set_property PACKAGE_PIN A4 [get_ports {pcie_7x_mgt_txp[0]}]
set_property PACKAGE_PIN A3 [get_ports {pcie_7x_mgt_txn[0]}]

set_property PACKAGE_PIN W13 [get_ports {usr_led_o_tri_o_tri_o[3]}]
set_property PACKAGE_PIN Y10 [get_ports {usr_led_o_tri_o_tri_o[2]}]
set_property PACKAGE_PIN V11 [get_ports {usr_led_o_tri_o_tri_o[1]}]
set_property PACKAGE_PIN W10 [get_ports {usr_led_o_tri_o_tri_o[0]}]
set_property PACKAGE_PIN Y20 [get_ports reset]
set_property PACKAGE_PIN D6 [get_ports {CLK_IN_D_clk_p[0]}]

set_property IOSTANDARD LVCMOS15 [get_ports reset]
set_property IOSTANDARD LVCMOS15 [get_ports {usr_led_o_tri_o_tri_o[3]}]
set_property IOSTANDARD LVCMOS15 [get_ports {usr_led_o_tri_o_tri_o[2]}]
set_property IOSTANDARD LVCMOS15 [get_ports {usr_led_o_tri_o_tri_o[1]}]
set_property IOSTANDARD LVCMOS15 [get_ports {usr_led_o_tri_o_tri_o[0]}]
set_property IOSTANDARD LVCMOS15 [get_ports sys_rst_n]

create_clock -period 10.000 -name clk_in -waveform {0.000 5.000} [list [get_ports *clk_*] [get_nets -hierarchical *sys_clk*]]
