# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7k160tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/asautaux/yarr/pcie_7x_0_example/pcie_7x_0_example.cache/wt [current_project]
set_property parent.project_path /home/asautaux/yarr/pcie_7x_0_example/pcie_7x_0_example.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
add_files -quiet /home/asautaux/yarr/pcie_7x_0_example/pcie_7x_0_example.srcs/sources_1/ip/pcie_7x_0/pcie_7x_0.dcp
set_property used_in_implementation false [get_files /home/asautaux/yarr/pcie_7x_0_example/pcie_7x_0_example.srcs/sources_1/ip/pcie_7x_0/pcie_7x_0.dcp]
read_verilog -library xil_defaultlib {
  /home/asautaux/yarr/pcie_7x_0_example/pcie_7x_0_example.srcs/sources_1/imports/pcie_7x_0/example_design/pcie_app_7x.v
  /home/asautaux/yarr/pcie_7x_0_example/pcie_7x_0_example.srcs/sources_1/imports/pcie_7x_0/example_design/xilinx_pcie_2_1_ep_7x.v
}
read_vhdl -library xil_defaultlib {
  /home/asautaux/yarr/pcie_7x_0_example/pcie_7x_0_example.srcs/sources_1/imports/sources_1/imports/sources_1/imports/sources_1/imports/new/simple_counter.vhd
  /home/asautaux/yarr/pcie_7x_0_example/pcie_7x_0_example.srcs/sources_1/imports/sources_1/imports/Downloads/bcf_bram_wbs.vhd
  /home/asautaux/yarr/pcie_7x_0_example/pcie_7x_0_example.srcs/sources_1/imports/sources_1/imports/Downloads/axis_rx.vhd
  /home/asautaux/yarr/pcie_7x_0_example/pcie_7x_0_example.srcs/sources_1/imports/sources_1/new/app.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/asautaux/yarr/pcie_7x_0_example/pcie_7x_0_example.srcs/constrs_1/imports/example_design/xilinx_pcie_7x_ep_x4g2.xdc
set_property used_in_implementation false [get_files /home/asautaux/yarr/pcie_7x_0_example/pcie_7x_0_example.srcs/constrs_1/imports/example_design/xilinx_pcie_7x_ep_x4g2.xdc]


synth_design -top xilinx_pcie_2_1_ep_7x -part xc7k160tfbg676-2


write_checkpoint -force -noxdef xilinx_pcie_2_1_ep_7x.dcp

catch { report_utilization -file xilinx_pcie_2_1_ep_7x_utilization_synth.rpt -pb xilinx_pcie_2_1_ep_7x_utilization_synth.pb }
