# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/example_design/xilinx_pcie_7x_ep_x4g2.xdc

# IP: ip/fifo_32x512/fifo_32x512.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_32x512 || ORIG_REF_NAME==fifo_32x512}]

# IP: ip/fifo_96x512/fifo_96x512.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_96x512 || ORIG_REF_NAME==fifo_96x512}]

# IP: ip/fifo_64x512/fifo_64x512.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_64x512 || ORIG_REF_NAME==fifo_64x512}]

# IP: ip/l2p_fifo64/l2p_fifo64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==l2p_fifo64 || ORIG_REF_NAME==l2p_fifo64}]

# IP: ip/ila_axis/ila_axis.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_axis || ORIG_REF_NAME==ila_axis}]

# IP: ip/ila_dma_ctrl_reg/ila_dma_ctrl_reg.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_dma_ctrl_reg || ORIG_REF_NAME==ila_dma_ctrl_reg}]

# IP: ip/ila_pd_pdm/ila_pd_pdm.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_pd_pdm || ORIG_REF_NAME==ila_pd_pdm}]

# IP: ip/ila_l2p_dma/ila_l2p_dma.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_l2p_dma || ORIG_REF_NAME==ila_l2p_dma}]

# IP: ip/ila_wsh_pipe/ila_wsh_pipe.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_wsh_pipe || ORIG_REF_NAME==ila_wsh_pipe}]

# IP: ip/pcie_7x_0/pcie_7x_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_7x_0 || ORIG_REF_NAME==pcie_7x_0}]
