# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k160tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/asautaux/yarr/project_tandem_1/project_tandem_1.cache/wt [current_project]
set_property parent.project_path /home/asautaux/yarr/project_tandem_1/project_tandem_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
add_files -quiet /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/fifo_32x512/fifo_32x512.dcp
set_property used_in_implementation false [get_files /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/fifo_32x512/fifo_32x512.dcp]
add_files -quiet /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/fifo_96x512/fifo_96x512.dcp
set_property used_in_implementation false [get_files /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/fifo_96x512/fifo_96x512.dcp]
add_files -quiet /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/fifo_64x512/fifo_64x512.dcp
set_property used_in_implementation false [get_files /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/fifo_64x512/fifo_64x512.dcp]
add_files -quiet /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/l2p_fifo64/l2p_fifo64.dcp
set_property used_in_implementation false [get_files /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/l2p_fifo64/l2p_fifo64.dcp]
add_files -quiet /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/ila_axis/ila_axis.dcp
set_property used_in_implementation false [get_files /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/ila_axis/ila_axis.dcp]
add_files -quiet /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/ila_dma_ctrl_reg/ila_dma_ctrl_reg.dcp
set_property used_in_implementation false [get_files /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/ila_dma_ctrl_reg/ila_dma_ctrl_reg.dcp]
add_files -quiet /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/ila_pd_pdm/ila_pd_pdm.dcp
set_property used_in_implementation false [get_files /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/ila_pd_pdm/ila_pd_pdm.dcp]
add_files -quiet /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/ila_l2p_dma/ila_l2p_dma.dcp
set_property used_in_implementation false [get_files /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/ila_l2p_dma/ila_l2p_dma.dcp]
add_files -quiet /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/ila_wsh_pipe/ila_wsh_pipe.dcp
set_property used_in_implementation false [get_files /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/ila_wsh_pipe/ila_wsh_pipe.dcp]
add_files -quiet /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/pcie_7x_0/pcie_7x_0.dcp
set_property used_in_implementation false [get_files /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/pcie_7x_0/pcie_7x_0.dcp]
read_ip -quiet /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/fifo_32x512/fifo_32x512.xci
set_property used_in_implementation false [get_files -all /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/fifo_32x512/fifo_32x512/fifo_32x512_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/fifo_32x512/fifo_32x512/fifo_32x512.xdc]
set_property used_in_implementation false [get_files -all /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/fifo_32x512/fifo_32x512_ooc.xdc]
set_property is_locked true [get_files /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/fifo_32x512/fifo_32x512.xci]

read_ip -quiet /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/fifo_96x512/fifo_96x512.xci
set_property used_in_implementation false [get_files -all /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/fifo_96x512/fifo_96x512/fifo_96x512_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/fifo_96x512/fifo_96x512/fifo_96x512.xdc]
set_property used_in_implementation false [get_files -all /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/fifo_96x512/fifo_96x512_ooc.xdc]
set_property is_locked true [get_files /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/fifo_96x512/fifo_96x512.xci]

read_ip -quiet /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/fifo_64x512/fifo_64x512.xci
set_property used_in_implementation false [get_files -all /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/fifo_64x512/fifo_64x512/fifo_64x512_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/fifo_64x512/fifo_64x512/fifo_64x512.xdc]
set_property used_in_implementation false [get_files -all /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/fifo_64x512/fifo_64x512_ooc.xdc]
set_property is_locked true [get_files /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/fifo_64x512/fifo_64x512.xci]

read_ip -quiet /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/l2p_fifo64/l2p_fifo64.xci
set_property used_in_implementation false [get_files -all /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/l2p_fifo64/l2p_fifo64/l2p_fifo64_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/l2p_fifo64/l2p_fifo64/l2p_fifo64.xdc]
set_property used_in_implementation false [get_files -all /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/l2p_fifo64/l2p_fifo64_ooc.xdc]
set_property is_locked true [get_files /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/l2p_fifo64/l2p_fifo64.xci]

read_ip -quiet /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/ila_axis/ila_axis.xci
set_property used_in_implementation false [get_files -all /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/ila_axis/ila_v6_1/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/ila_axis/ila_axis_ooc.xdc]
set_property is_locked true [get_files /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/ila_axis/ila_axis.xci]

read_ip -quiet /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/ila_dma_ctrl_reg/ila_dma_ctrl_reg.xci
set_property used_in_implementation false [get_files -all /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/ila_dma_ctrl_reg/ila_v6_1/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/ila_dma_ctrl_reg/ila_dma_ctrl_reg_ooc.xdc]
set_property is_locked true [get_files /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/ila_dma_ctrl_reg/ila_dma_ctrl_reg.xci]

read_ip -quiet /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/ila_pd_pdm/ila_pd_pdm.xci
set_property used_in_implementation false [get_files -all /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/ila_pd_pdm/ila_v6_1/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/ila_pd_pdm/ila_pd_pdm_ooc.xdc]
set_property is_locked true [get_files /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/ila_pd_pdm/ila_pd_pdm.xci]

read_ip -quiet /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/ila_l2p_dma/ila_l2p_dma.xci
set_property used_in_implementation false [get_files -all /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/ila_l2p_dma/ila_v6_1/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/ila_l2p_dma/ila_l2p_dma_ooc.xdc]
set_property is_locked true [get_files /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/ila_l2p_dma/ila_l2p_dma.xci]

read_ip -quiet /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/ila_wsh_pipe/ila_wsh_pipe.xci
set_property used_in_implementation false [get_files -all /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/ila_wsh_pipe/ila_v6_1/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/ila_wsh_pipe/ila_wsh_pipe_ooc.xdc]
set_property is_locked true [get_files /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/ila_wsh_pipe/ila_wsh_pipe.xci]

read_ip -quiet /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/pcie_7x_0/pcie_7x_0.xci
set_property used_in_implementation false [get_files -all /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/pcie_7x_0/ip_0/pcie_7x_0_fastConfigFIFO/pcie_7x_0_fastConfigFIFO_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/pcie_7x_0/ip_0/pcie_7x_0_fastConfigFIFO/pcie_7x_0_fastConfigFIFO.xdc]
set_property used_in_implementation false [get_files -all /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/pcie_7x_0/ip_0/pcie_7x_0_fastConfigFIFO_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/pcie_7x_0/source/pcie_7x_0-PCIE_X0Y0.xdc]
set_property used_in_implementation false [get_files -all /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/pcie_7x_0/synth/pcie_7x_0_ooc.xdc]
set_property is_locked true [get_files /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/ip/pcie_7x_0/pcie_7x_0.xci]

read_verilog -library xil_defaultlib /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/imports/pcie_7x_0/example_design/xilinx_pcie_2_1_ep_7x.v
read_vhdl -library xil_defaultlib {
  /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/imports/sources_1/imports/common/gn4124_core_pkg.vhd
  /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/imports/sources_1/imports/yarr_sim/l2p_dma/l2p_fifo.vhd
  /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/imports/sources_1/imports/yarr_sim/p2l_dma/generic_async_fifo_wrapper.vhd
  /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/imports/sources_1/imports/yarr_sim/top/dma_controller_wb_slave.vhd
  /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/imports/sources_1/imports/common/common_pkg.vhd
  /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/imports/sources_1/imports/Downloads/wbmaster32.vhd
  /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/imports/new/simple_counter.vhd
  /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/imports/sources_1/imports/yarr_sim/p2l_dma/p2l_dma_master.vhd
  /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/imports/Downloads/p2l_decoder.vhd
  /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/imports/sources_1/imports/yarr_sim/l2p_dma/l2p_dma_master.vhd
  /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/imports/sources_1/imports/Downloads/l2p_arbiter.vhd
  /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/imports/sources_1/new/k_bram.vhd
  /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/imports/sources_1/imports/yarr_sim/top/dma_controller.vhd
  /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/imports/sources_1/new/bcf_bram32.vhd
  /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/sources_1/imports/top/app.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/constrs_1/imports/example_design/xilinx_pcie_7x_ep_x4g2.xdc
set_property used_in_implementation false [get_files /home/asautaux/yarr/project_tandem_1/project_tandem_1.srcs/constrs_1/imports/example_design/xilinx_pcie_7x_ep_x4g2.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top xilinx_pcie_2_1_ep_7x -part xc7k160tfbg676-2


write_checkpoint -force -noxdef xilinx_pcie_2_1_ep_7x.dcp

catch { report_utilization -file xilinx_pcie_2_1_ep_7x_utilization_synth.rpt -pb xilinx_pcie_2_1_ep_7x_utilization_synth.pb }
