# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7k160tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/asautaux/yarr/simple_pcie/simple_pcie.cache/wt [current_project]
set_property parent.project_path /home/asautaux/yarr/simple_pcie/simple_pcie.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property include_dirs {
  /home/asautaux/vhdl/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/quickpcie/include/common
  {/home/asautaux/vhdl/quickpcie-expert_gen2_v156_b085_xilinx_eval/ref_design/synthesis/xilinx/plda_xpressk7_xc7k160tfbg676-2/x4_gen2/vlog/;}
  /home/asautaux/vhdl/quickpcie-expert_gen2_v156_b085_xilinx_eval/ref_design/source/endpoint/design/wrapper/k7/qpcie_ipcore_x4_gen2
} [current_fileset]
add_files -quiet /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/ip/ila_0_1/ila_0.dcp
set_property used_in_implementation false [get_files /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/ip/ila_0_1/ila_0.dcp]
add_files -quiet /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/ip/ila_1/ila_1.dcp
set_property used_in_implementation false [get_files /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/ip/ila_1/ila_1.dcp]
add_files -quiet /home/asautaux/yarr/simple_pcie/simple_pcie.runs/qpcie_ipcore_x4_gen2_synth_1/qpcie_ipcore_x4_gen2.dcp
set_property used_in_implementation false [get_files /home/asautaux/yarr/simple_pcie/simple_pcie.runs/qpcie_ipcore_x4_gen2_synth_1/qpcie_ipcore_x4_gen2.dcp]
add_files -quiet /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/ip/ila_2/ila_2.dcp
set_property used_in_implementation false [get_files /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/ip/ila_2/ila_2.dcp]
add_files -quiet /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/ip/ila_3/ila_3.dcp
set_property used_in_implementation false [get_files /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/ip/ila_3/ila_3.dcp]
read_verilog -library xil_defaultlib {
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_pcie_bram_7x.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_gtp_cpllpd_ovrd.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_rxeq_scan.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_qpll_wrapper.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_qpll_drp.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_pcie_brams_7x.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_gtx_cpllpd_ovrd.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_axi_basic_tx_thrtl_ctl.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_axi_basic_tx_pipeline.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_axi_basic_rx_pipeline.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_axi_basic_rx_null_gen.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_qpll_reset.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_pipe_user.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_pipe_sync.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_pipe_reset.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_pipe_rate.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_pipe_eq.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_pipe_drp.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_pcie_pipe_misc.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_pcie_pipe_lane.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_pcie_bram_top_7x.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_gt_wrapper.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_gt_common.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_gtp_pipe_reset.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_gtp_pipe_rate.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_gtp_pipe_drp.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_axi_basic_tx.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_axi_basic_rx.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_pipe_wrapper.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_pcie_pipe_pipeline.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_pcie_7x.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_gt_rx_valid_filter_7x.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_axi_basic_top.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_pcie_top.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_gt_top.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_core_top.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/synthesis/xilinx/vlog/qpcie_lib.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/ref_design/source/endpoint/design/ref_design/qpcie_axi4lite_dec.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/ref_design/source/endpoint/design/ref_design/qpcie_external_reg.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/ref_design/source/endpoint/design/ref_design/qpcie_axi4slv_ram.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/ref_design/source/endpoint/design/ref_design/qpcie_scfifo.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/ref_design/source/endpoint/design/ref_design/qpcie_ref_design.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/ref_design/source/endpoint/design/top/qpcie_xilinx_top_x4_gen2.v
  /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/imports/quickpcie-expert_gen2_v156_b085_xilinx_eval/core/source/vlog/hip/s7/source/pcie_7x_0_pcie2_top.v
}
read_vhdl -library xil_defaultlib /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/sources_1/new/simple_pci_top.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/constrs_1/imports/vlog/qpcie_ref_design.xdc
set_property used_in_implementation false [get_files /home/asautaux/yarr/simple_pcie/simple_pcie.srcs/constrs_1/imports/vlog/qpcie_ref_design.xdc]


synth_design -top simple_pci_top -part xc7k160tfbg676-2


write_checkpoint -force -noxdef simple_pci_top.dcp

catch { report_utilization -file simple_pci_top_utilization_synth.rpt -pb simple_pci_top_utilization_synth.pb }
