# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/asautaux/yarr/project_pcie_5/project_pcie_5.srcs/sources_1/ip/ila_l2p_dma/ila_l2p_dma.xci
# IP: The module: 'ila_l2p_dma' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/asautaux/yarr/project_pcie_5/project_pcie_5.srcs/sources_1/ip/ila_l2p_dma/ila_v6_1/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_l2p_dma'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/asautaux/yarr/project_pcie_5/project_pcie_5.srcs/sources_1/ip/ila_l2p_dma/ila_l2p_dma_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_l2p_dma'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/asautaux/yarr/project_pcie_5/project_pcie_5.srcs/sources_1/ip/ila_l2p_dma/ila_l2p_dma.xci
# IP: The module: 'ila_l2p_dma' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/asautaux/yarr/project_pcie_5/project_pcie_5.srcs/sources_1/ip/ila_l2p_dma/ila_v6_1/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_l2p_dma'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/asautaux/yarr/project_pcie_5/project_pcie_5.srcs/sources_1/ip/ila_l2p_dma/ila_l2p_dma_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_l2p_dma'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
